name: Deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: infra/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_APP_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_APP_NAME: ${{ secrets.DOCKER_APP_NAME }}
          DOCKER_IMAGE_TAG: latest
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: DOCKER_REGISTRY,DOCKER_APP_NAME,DOCKER_IMAGE_TAG
          script: |
            cd ${{ vars.DEPLOY_PATH }}
            chmod +x infra/deploy.sh
            ./infra/deploy.sh
